version: '2'

services:

  web:
    build: ./
    image: __ORG__/__REPO__
    depends_on:
      - redis
      - mysql
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - /var/www/html/node_modules
    env_file: .env
    environment:
      - APP_TYPE=web
    
  worker:
    build: ./
    image: __ORG__/__REPO__
    depends_on:
      - redis
      - mysql
    ports:
      - "81:80"
    volumes:
      - .:/var/www/html
      - /var/www/html/node_modules
    env_file: .env
    environment:
      - APP_TYPE=worker

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always 
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret

  redis:
    image: redis:3.2
    ports:
      - "6379:6379"